gravatar_devise_WORKING/config/routes.rb
Rails.application.routes.draw do
  resources :rabbits
  devise_for :users

end

gravatar_devise_WORKING/app/models/rabbit.rb
class Rabbit < ActiveRecord::Base
end

gravatar_devise_WORKING/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  include Gravtastic
  gravtastic

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

gravatar_devise_WORKING/app/controllers/rabbits_controller.rb
class RabbitsController < ApplicationController
  before_action :set_rabbit, only: [:show, :edit, :update, :destroy]

  # GET /rabbits
  # GET /rabbits.json
  def index
    @rabbits = Rabbit.all
  end

  # GET /rabbits/1
  # GET /rabbits/1.json
  def show
  end

  # GET /rabbits/new
  def new
    @rabbit = Rabbit.new
  end

  # GET /rabbits/1/edit
  def edit
  end

  # POST /rabbits
  # POST /rabbits.json
  def create
    @rabbit = Rabbit.new(rabbit_params)

    respond_to do |format|
      if @rabbit.save
        format.html { redirect_to @rabbit, notice: 'Rabbit was successfully created.' }
        format.json { render :show, status: :created, location: @rabbit }
      else
        format.html { render :new }
        format.json { render json: @rabbit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rabbits/1
  # PATCH/PUT /rabbits/1.json
  def update
    respond_to do |format|
      if @rabbit.update(rabbit_params)
        format.html { redirect_to @rabbit, notice: 'Rabbit was successfully updated.' }
        format.json { render :show, status: :ok, location: @rabbit }
      else
        format.html { render :edit }
        format.json { render json: @rabbit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rabbits/1
  # DELETE /rabbits/1.json
  def destroy
    @rabbit.destroy
    respond_to do |format|
      format.html { redirect_to rabbits_url, notice: 'Rabbit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rabbit
      @rabbit = Rabbit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rabbit_params
      params.require(:rabbit).permit(:name)
    end
end

gravatar_devise_WORKING/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GravatarDeviseNotworking</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if user_signed_in? %>
  <li>
  <%= image_tag current_user.gravatar_url(default: "identicon") %>
  <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>        
  </li>
<% else %>
  <li>
  <%= link_to('Login', new_user_session_path)  %>  
  </li>
<% end %>

<%= yield %>

</body>
</html>

gravatar_devise_WORKING/app/views/rabbits/_form.html.erb
<%= form_for(@rabbit) do |f| %>
  <% if @rabbit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rabbit.errors.count, "error") %> prohibited this rabbit from being saved:</h2>

      <ul>
      <% @rabbit.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

gravatar_devise_WORKING/app/views/rabbits/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Rabbits</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rabbits.each do |rabbit| %>
      <tr>
        <td><%= rabbit.name %></td>
        <td><%= link_to 'Show', rabbit %></td>
        <td><%= link_to 'Edit', edit_rabbit_path(rabbit) %></td>
        <td><%= link_to 'Destroy', rabbit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rabbit', new_rabbit_path %>

gravatar_devise_WORKING/app/views/rabbits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @rabbit.name %>
</p>

<%= link_to 'Edit', edit_rabbit_path(@rabbit) %> |
<%= link_to 'Back', rabbits_path %>